version: '3.8'
services:
  db:
    container_name: pg_container_fastapi
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi_db
    volumes:
      - ./postgres_data/var/lib/postgresql/data
    ports:
      - "5434:5434"
  pgadmin:
    container_name: pgadmin4_container_fastapi
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
